<?php
/**
 * Demo product catalogue. Prices, stock and specifications are illustrative
 * placeholders. Brand names identify compatible hardware types only; the
 * demo store notice states that no affiliation or reseller status is implied.
 *
 * Fields: name, sku, cat, brand, img, price, sale, stock (-1 = not tracked),
 * featured, short, attrs, specs (label "#Group" = heading), warranty,
 * downloads, virtual, variable (attribute => [value => [price, stock]]),
 * cross (SKUs), up (SKUs).
 *
 * @package PallthemeCore
 */

defined( 'ABSPATH' ) || exit;

/**
 * Products.
 *
 * @return array<int,array<string,mixed>>
 */
function pallcore_demo_products(): array {
	return array(
		// ------------------------------------------------------------ Servers.
		array( 'name' => 'Dell PowerEdge R760 Enterprise Server', 'sku' => 'TN-SRV-R760', 'cat' => 'Servers', 'brand' => 'Dell', 'img' => 'server', 'price' => '8499', 'sale' => '7899', 'stock' => 6, 'featured' => true,
			'short' => 'Dual-socket 2U rack server for virtualization, databases and AI inference.',
			'attrs' => array( 'Processor' => 'Intel Xeon Gold', 'RAM' => '128GB', 'Storage' => 'NVMe', 'Form Factor' => '2U Rack', 'Warranty' => '3 Years' ),
			'specs' => array( array( '#Compute', '' ), array( 'Processor', '2 × Intel Xeon Gold 6430 (32C, 2.1 GHz)' ), array( 'Memory', '128GB DDR5-4800 ECC RDIMM (8 × 16GB)' ), array( '#Storage', '' ), array( 'Storage', '2 × 1.92TB NVMe SSD, RAID 1' ), array( 'Drive bays', '8 × 2.5" NVMe/SAS' ), array( '#Connectivity', '' ), array( 'Network', '2 × 25GbE SFP28 OCP 3.0' ), array( 'Management', 'Integrated out-of-band controller' ), array( '#Power & chassis', '' ), array( 'Power', '2 × 1100W redundant, Platinum' ), array( 'Form factor', '2U rack' ), array( 'Warranty', '3 years next-business-day on-site' ) ),
			'warranty' => '3 years next-business-day on-site support', 'downloads' => true, 'cross' => array( 'TN-RAM-DDR5', 'TN-SSD-NVME-U2', 'TN-UPS-3K', 'TN-LIC-DC16' ), 'up' => array( 'TN-SRV-VH1U' ) ),
		array( 'name' => 'HPE ProLiant DL380 Gen11 Server', 'sku' => 'TN-SRV-DL380', 'cat' => 'Servers', 'brand' => 'HPE', 'img' => 'server-alt', 'price' => '7990', 'sale' => '', 'stock' => 4, 'featured' => false,
			'short' => 'Versatile 2U workhorse for mixed virtualized workloads and storage-heavy applications.',
			'attrs' => array( 'Processor' => 'Intel Xeon Silver', 'RAM' => '64GB', 'Storage' => 'SAS SSD', 'Form Factor' => '2U Rack', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Processor', '2 × Intel Xeon Silver 4410Y (12C, 2.0 GHz)' ), array( 'Memory', '64GB DDR5-4800 ECC RDIMM' ), array( 'Storage', '4 × 960GB SAS SSD, hardware RAID' ), array( 'Network', '4 × 1GbE + 2 × 10GbE SFP+' ), array( 'Power', '2 × 800W redundant' ), array( 'Form factor', '2U rack' ), array( 'Warranty', '3 years' ) ),
			'warranty' => '3 years parts and labour', 'downloads' => true, 'cross' => array( 'TN-RAM-DDR4-32', 'TN-SSD-3840', 'TN-NIC-10G' ) ),
		array( 'name' => 'Virtualization Host Server 1U (Dual EPYC)', 'sku' => 'TN-SRV-VH1U', 'cat' => 'Servers', 'brand' => 'TechNova Labs', 'img' => 'server1u', 'price' => '11250', 'sale' => '', 'stock' => 3, 'featured' => true,
			'short' => 'High-density 1U host pre-built and burn-in tested for Proxmox VE, VMware or Hyper-V clusters.',
			'attrs' => array( 'Processor' => 'AMD EPYC', 'RAM' => '256GB', 'Storage' => 'NVMe', 'Form Factor' => '1U Rack', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Processor', '2 × AMD EPYC 9354 (32C, 3.25 GHz)' ), array( 'Memory', '256GB DDR5-4800 ECC (16 × 16GB)' ), array( 'Boot', '2 × 480GB M.2 NVMe, mirrored' ), array( 'Data', '4 × 3.84TB U.2 NVMe' ), array( 'Network', '2 × 25GbE SFP28 + 2 × 1GbE' ), array( 'Hypervisor', 'Pre-installed on request' ), array( 'Form factor', '1U rack' ), array( 'Warranty', '3 years advance replacement' ) ),
			'warranty' => '3 years advance parts replacement', 'downloads' => true, 'cross' => array( 'TN-SW-25G-48', 'TN-SFP-25G-SR', 'TN-SVC-LINUX-SUP' ) ),
		array( 'name' => 'Lenovo ThinkSystem ST250 V3 Tower Server', 'sku' => 'TN-SRV-ST250', 'cat' => 'Servers', 'brand' => 'Lenovo', 'img' => 'tower', 'price' => '2390', 'sale' => '2190', 'stock' => 8, 'featured' => false,
			'short' => 'Quiet single-socket tower server for small offices, file sharing and branch workloads.',
			'attrs' => array( 'Processor' => 'Intel Xeon E', 'RAM' => '32GB', 'Storage' => 'SATA SSD', 'Form Factor' => 'Tower', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Processor', 'Intel Xeon E-2434 (4C, 3.4 GHz)' ), array( 'Memory', '32GB DDR5 ECC' ), array( 'Storage', '2 × 960GB SATA SSD, RAID 1' ), array( 'Network', '2 × 1GbE' ), array( 'Power', '500W' ), array( 'Form factor', 'Tower (rack-convertible)' ) ),
			'warranty' => '3 years on-site', 'downloads' => false, 'cross' => array( 'TN-UPS-3K', 'TN-HDD-12T' ) ),

		// ----------------------------------------------------------- Switches.
		array( 'name' => 'Cisco Catalyst 9300 48-Port Switch', 'sku' => 'TN-SW-C9300-48', 'cat' => 'Switches', 'brand' => 'Cisco', 'img' => 'switch', 'price' => '5290', 'sale' => '', 'stock' => 12, 'featured' => true,
			'short' => 'Stackable enterprise access switch with 48 × 1GbE ports and modular 10GbE uplinks.',
			'attrs' => array( 'Port Speed' => '1GbE', 'Interface' => 'RJ45', 'Form Factor' => '1U Rack', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Ports', '48 × 1GbE RJ45' ), array( 'Uplinks', '4 × 10GbE SFP+ (network module)' ), array( 'Switching capacity', '256 Gbps' ), array( 'Stacking', 'Up to 8 members' ), array( 'Layer', 'Layer 3' ), array( 'Power', '715W field-replaceable PSU' ) ),
			'warranty' => 'Limited lifetime hardware warranty', 'downloads' => true, 'cross' => array( 'TN-SFP-10G-SR', 'TN-FIB-OM4' ), 'up' => array( 'TN-SW-25G-48' ) ),
		array( 'name' => 'Enterprise 25GbE Data Center Switch (48 × SFP28)', 'sku' => 'TN-SW-25G-48', 'cat' => 'Switches', 'brand' => 'Juniper', 'img' => 'switch-core', 'price' => '14900', 'sale' => '13950', 'stock' => 2, 'featured' => true,
			'short' => 'Leaf switch with 48 × 25GbE SFP28 and 8 × 100GbE QSFP28 for spine-leaf fabrics.',
			'attrs' => array( 'Port Speed' => '25GbE', 'Interface' => 'SFP28', 'Form Factor' => '1U Rack', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'Ports', '48 × 25GbE SFP28' ), array( 'Uplinks', '8 × 100GbE QSFP28' ), array( 'Throughput', '4 Tbps' ), array( 'Latency', 'Sub-microsecond' ), array( 'Features', 'VXLAN EVPN, BGP, MC-LAG' ), array( 'Power', '2 × hot-swap PSU, front-to-back airflow' ) ),
			'warranty' => '1 year hardware, extendable', 'downloads' => true, 'cross' => array( 'TN-SFP-25G-SR', 'TN-QSFP-100G', 'TN-FIB-MPO12' ) ),
		array( 'name' => 'Managed 10GbE Switch (24 × SFP+)', 'sku' => 'TN-SW-10G-24', 'cat' => 'Switches', 'brand' => 'MikroTik', 'img' => 'switch10g', 'price' => '899', 'sale' => '849', 'stock' => 15, 'featured' => false,
			'short' => 'Cost-effective 24-port 10GbE SFP+ aggregation switch with 40GbE uplinks.',
			'attrs' => array( 'Port Speed' => '10GbE', 'Interface' => 'SFP+', 'Form Factor' => '1U Rack', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'Ports', '24 × 10GbE SFP+' ), array( 'Uplinks', '2 × 40GbE QSFP+' ), array( 'Switching capacity', '640 Gbps' ), array( 'Management', 'Web, CLI, SNMP' ), array( 'Power', 'Dual redundant PSU' ) ),
			'warranty' => '1 year', 'downloads' => false, 'cross' => array( 'TN-SFP-10G-SR', 'TN-NIC-10G' ) ),
		array( 'name' => 'PoE+ Access Switch 24-Port', 'sku' => 'TN-SW-POE24', 'cat' => 'Switches', 'brand' => 'Juniper', 'img' => 'switch-poe', 'price' => '1690', 'sale' => '', 'stock' => 10, 'featured' => false,
			'short' => '24 × 1GbE PoE+ access switch for wireless access points, cameras and IP phones.',
			'attrs' => array( 'Port Speed' => '1GbE', 'Interface' => 'RJ45', 'Form Factor' => '1U Rack', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Ports', '24 × 1GbE PoE+ (802.3at)' ), array( 'PoE budget', '370W' ), array( 'Uplinks', '4 × 10GbE SFP+' ), array( 'Layer', 'Layer 2+/3 lite' ), array( 'Management', 'Cloud or local' ) ),
			'warranty' => 'Limited lifetime', 'downloads' => false, 'cross' => array( 'TN-AP-WIFI6E' ) ),

		// ------------------------------------------------------------ Routers.
		array( 'name' => 'MikroTik Router Appliance (CCR2116)', 'sku' => 'TN-RT-CCR2116', 'cat' => 'Routers', 'brand' => 'MikroTik', 'img' => 'router', 'price' => '995', 'sale' => '', 'stock' => 18, 'featured' => true,
			'short' => '16-core ARM router with 25GbE SFP28 for ISP edges and enterprise WAN.',
			'attrs' => array( 'Port Speed' => '25GbE', 'Interface' => 'SFP28', 'Form Factor' => '1U Rack', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'CPU', '16-core ARM, 2 GHz' ), array( 'Memory', '16GB DDR4' ), array( 'Ports', '13 × 1GbE, 4 × 10GbE SFP+, 1 × 25GbE SFP28' ), array( 'Routing', 'BGP, OSPF, MPLS' ), array( 'Power', 'Dual redundant PSU' ) ),
			'warranty' => '1 year', 'downloads' => true, 'cross' => array( 'TN-SFP-10G-SR', 'TN-SFP-25G-SR' ) ),
		array( 'name' => 'Juniper MX204 Edge Router', 'sku' => 'TN-RT-MX204', 'cat' => 'Routers', 'brand' => 'Juniper', 'img' => 'router-edge', 'price' => '28900', 'sale' => '', 'stock' => 1, 'featured' => false,
			'short' => 'Compact 1U carrier-grade edge router with 100GbE interfaces for peering and transit.',
			'attrs' => array( 'Port Speed' => '100GbE', 'Interface' => 'QSFP28', 'Form Factor' => '1U Rack', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'Ports', '4 × 100GbE QSFP28 + 8 × 10GbE SFP+' ), array( 'Throughput', 'Up to 400 Gbps' ), array( 'Routing', 'Full Internet table, BGP, MPLS, segment routing' ), array( 'Power', 'Redundant AC or DC' ) ),
			'warranty' => '1 year hardware', 'downloads' => false, 'cross' => array( 'TN-QSFP-100G' ) ),

		// ---------------------------------------------------------- Firewalls.
		array( 'name' => 'Enterprise Firewall Appliance (FortiGate 100F)', 'sku' => 'TN-FW-100F', 'cat' => 'Firewalls', 'brand' => 'Fortinet', 'img' => 'firewall', 'price' => '3150', 'sale' => '2890', 'stock' => 4, 'featured' => true,
			'short' => 'Next-generation firewall with SD-WAN, SSL inspection and intrusion prevention for mid-size sites.',
			'attrs' => array( 'Port Speed' => '10GbE', 'Interface' => 'SFP+', 'Form Factor' => '1U Rack', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'Firewall throughput', '20 Gbps' ), array( 'Threat protection', '1 Gbps' ), array( 'IPsec VPN', '11.5 Gbps' ), array( 'Interfaces', '22 × 1GbE, 4 × 10GbE SFP+' ), array( 'Concurrent sessions', '1.5 million' ) ),
			'warranty' => '1 year hardware; security subscriptions sold separately', 'downloads' => true, 'cross' => array( 'TN-SVC-SEC-ASSESS', 'TN-SFP-10G-SR' ) ),
		array( 'name' => 'Branch Firewall Appliance (FortiGate 40F)', 'sku' => 'TN-FW-40F', 'cat' => 'Firewalls', 'brand' => 'Fortinet', 'img' => 'firewall-desktop', 'price' => '549', 'sale' => '', 'stock' => 20, 'featured' => false,
			'short' => 'Desktop next-generation firewall for small offices and branch sites with SD-WAN.',
			'attrs' => array( 'Port Speed' => '1GbE', 'Interface' => 'RJ45', 'Form Factor' => 'Desktop', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'Firewall throughput', '5 Gbps' ), array( 'Threat protection', '600 Mbps' ), array( 'Interfaces', '5 × 1GbE' ), array( 'Form factor', 'Desktop, fanless' ) ),
			'warranty' => '1 year', 'downloads' => false, 'cross' => array( 'TN-SW-POE24' ) ),

		// ------------------------------------------------------ Network cards.
		array( 'name' => '25GbE SFP28 Dual-Port Network Adapter', 'sku' => 'TN-NIC-25G', 'cat' => 'Network Cards', 'brand' => 'Intel', 'img' => 'nic', 'price' => '429', 'sale' => '', 'stock' => 30, 'featured' => false,
			'short' => 'PCIe 4.0 dual-port 25GbE adapter with RDMA support for virtualization and storage networks.',
			'attrs' => array( 'Port Speed' => '25GbE', 'Interface' => 'SFP28', 'Form Factor' => 'PCIe', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Ports', '2 × 25GbE SFP28' ), array( 'Host interface', 'PCIe 4.0 x8' ), array( 'Features', 'RDMA (RoCEv2), SR-IOV' ), array( 'Bracket', 'Full and low profile included' ) ),
			'warranty' => '3 years', 'downloads' => true, 'cross' => array( 'TN-SFP-25G-SR' ) ),
		array( 'name' => '10GbE SFP+ Dual-Port Network Adapter', 'sku' => 'TN-NIC-10G', 'cat' => 'Network Cards', 'brand' => 'Intel', 'img' => 'nic-10g', 'price' => '219', 'sale' => '199', 'stock' => 40, 'featured' => false,
			'short' => 'Reliable dual-port 10GbE adapter for servers and workstations.',
			'attrs' => array( 'Port Speed' => '10GbE', 'Interface' => 'SFP+', 'Form Factor' => 'PCIe', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Ports', '2 × 10GbE SFP+' ), array( 'Host interface', 'PCIe 3.0 x8' ), array( 'Features', 'SR-IOV, VXLAN offload' ) ),
			'warranty' => '3 years', 'downloads' => false, 'cross' => array( 'TN-SFP-10G-SR' ) ),

		// ------------------------------------------------------- Transceivers.
		array( 'name' => '10G SFP+ SR Optical Module', 'sku' => 'TN-SFP-10G-SR', 'cat' => 'Transceivers', 'brand' => 'TechNova Labs', 'img' => 'sfp', 'price' => '29', 'sale' => '', 'stock' => 300, 'featured' => true,
			'short' => 'Multi-mode 850 nm optic, up to 300 m on OM3 / 400 m on OM4, coded for major switch vendors.',
			'attrs' => array( 'Port Speed' => '10GbE', 'Interface' => 'SFP+', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Data rate', '10.3125 Gbps' ), array( 'Wavelength', '850 nm' ), array( 'Distance', '300 m (OM3) / 400 m (OM4)' ), array( 'Connector', 'Duplex LC' ), array( 'DDM', 'Supported' ) ),
			'warranty' => 'Lifetime replacement', 'downloads' => false, 'cross' => array( 'TN-FIB-OM4' ) ),
		array( 'name' => '25G SFP28 SR Optical Module', 'sku' => 'TN-SFP-25G-SR', 'cat' => 'Transceivers', 'brand' => 'TechNova Labs', 'img' => 'sfp28', 'price' => '59', 'sale' => '', 'stock' => 200, 'featured' => false,
			'short' => '25GbE short-reach optic for leaf-to-server links up to 100 m on OM4.',
			'attrs' => array( 'Port Speed' => '25GbE', 'Interface' => 'SFP28', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Data rate', '25.78 Gbps' ), array( 'Wavelength', '850 nm' ), array( 'Distance', '70 m (OM3) / 100 m (OM4)' ), array( 'Connector', 'Duplex LC' ) ),
			'warranty' => 'Lifetime replacement', 'downloads' => false, 'cross' => array( 'TN-FIB-OM4' ) ),
		array( 'name' => '100G QSFP28 SR4 Optical Module', 'sku' => 'TN-QSFP-100G', 'cat' => 'Transceivers', 'brand' => 'TechNova Labs', 'img' => 'qsfp', 'price' => '179', 'sale' => '159', 'stock' => 60, 'featured' => false,
			'short' => '100GbE parallel optic for spine-leaf uplinks over MPO-12 multi-mode fiber.',
			'attrs' => array( 'Port Speed' => '100GbE', 'Interface' => 'QSFP28', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Data rate', '4 × 25.78 Gbps' ), array( 'Wavelength', '850 nm' ), array( 'Distance', '100 m (OM4)' ), array( 'Connector', 'MPO-12' ) ),
			'warranty' => 'Lifetime replacement', 'downloads' => false, 'cross' => array( 'TN-FIB-MPO12' ) ),

		// ------------------------------------------------------- Fiber optics.
		array( 'name' => 'OM4 LC-LC Duplex Fiber Patch Cord', 'sku' => 'TN-FIB-OM4', 'cat' => 'Fiber Optics', 'brand' => 'TechNova Labs', 'img' => 'fiber', 'price' => '', 'sale' => '', 'stock' => -1, 'featured' => false,
			'variable' => array( 'Length' => array( '1m' => array( '9', 400 ), '3m' => array( '12', 500 ), '5m' => array( '15', 300 ), '10m' => array( '22', 120 ) ) ),
			'short' => 'Low-loss OM4 multi-mode patch cord for 10/25/40/100GbE links. Choose your length.',
			'attrs' => array( 'Interface' => 'LC', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Fiber', 'OM4 50/125 µm' ), array( 'Connectors', 'LC-UPC to LC-UPC' ), array( 'Insertion loss', '≤ 0.3 dB' ), array( 'Jacket', 'LSZH, aqua' ) ),
			'warranty' => 'Lifetime', 'downloads' => false ),
		array( 'name' => 'MPO-12 Trunk Cable 10m', 'sku' => 'TN-FIB-MPO12', 'cat' => 'Fiber Optics', 'brand' => 'TechNova Labs', 'img' => 'mpo', 'price' => '89', 'sale' => '', 'stock' => 50, 'featured' => false,
			'short' => 'Pre-terminated 12-fiber OM4 trunk for 40/100GbE parallel optics.',
			'attrs' => array( 'Interface' => 'MPO', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Fiber count', '12' ), array( 'Type', 'OM4, Type B polarity' ), array( 'Length', '10 m' ), array( 'Connectors', 'MPO female to MPO female' ) ),
			'warranty' => 'Lifetime', 'downloads' => false ),

		// ---------------------------------------------------------------- SSD.
		array( 'name' => '1.92TB Enterprise NVMe SSD (U.2)', 'sku' => 'TN-SSD-NVME-U2', 'cat' => 'SSD', 'brand' => 'Micron', 'img' => 'u2', 'price' => '389', 'sale' => '359', 'stock' => 45, 'featured' => true,
			'short' => 'PCIe 4.0 U.2 NVMe drive with power-loss protection for mixed-use server workloads.',
			'attrs' => array( 'Capacity' => '1.92TB', 'Interface' => 'NVMe', 'Form Factor' => '2.5 inch U.2', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Capacity', '1.92TB' ), array( 'Interface', 'PCIe 4.0 x4 NVMe' ), array( 'Sequential read', '6,800 MB/s' ), array( 'Random read', '800K IOPS' ), array( 'Endurance', '1 DWPD' ), array( 'Power-loss protection', 'Yes' ) ),
			'warranty' => '5 years', 'downloads' => true ),
		array( 'name' => 'Enterprise SAS SSD 3.84TB', 'sku' => 'TN-SSD-3840', 'cat' => 'SSD', 'brand' => 'Samsung', 'img' => 'ssd', 'price' => '689', 'sale' => '629', 'stock' => 40, 'featured' => false,
			'short' => 'Read-intensive 2.5" 12Gb/s SAS SSD for servers and storage arrays.',
			'attrs' => array( 'Capacity' => '3.84TB', 'Interface' => 'SAS', 'Form Factor' => '2.5 inch', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Capacity', '3.84TB' ), array( 'Interface', 'SAS 12Gb/s' ), array( 'Sequential read', '2,100 MB/s' ), array( 'Random read', '420K IOPS' ), array( 'Endurance', '1 DWPD' ) ),
			'warranty' => '5 years', 'downloads' => false ),
		array( 'name' => 'NVMe M.2 2TB Gen4 SSD', 'sku' => 'TN-NVME-2T', 'cat' => 'SSD', 'brand' => 'Kingston', 'img' => 'nvme', 'price' => '219', 'sale' => '199', 'stock' => 60, 'featured' => false,
			'short' => 'PCIe 4.0 M.2 drive with up to 7,000 MB/s reads for boot volumes and workstations.',
			'attrs' => array( 'Capacity' => '2TB', 'Interface' => 'NVMe', 'Form Factor' => 'M.2 2280', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Capacity', '2TB' ), array( 'Interface', 'PCIe 4.0 x4 NVMe' ), array( 'Sequential read', '7,000 MB/s' ), array( 'Sequential write', '5,100 MB/s' ) ),
			'warranty' => '5 years', 'downloads' => false ),

		// ---------------------------------------------------------------- HDD.
		array( 'name' => '18TB Enterprise SATA HDD', 'sku' => 'TN-HDD-18T', 'cat' => 'HDD', 'brand' => 'Seagate', 'img' => 'hdd', 'price' => '379', 'sale' => '', 'stock' => 35, 'featured' => false,
			'short' => '7,200 rpm enterprise hard drive for capacity tiers, backup and surveillance storage.',
			'attrs' => array( 'Capacity' => '18TB', 'Interface' => 'SATA', 'Form Factor' => '3.5 inch', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Capacity', '18TB' ), array( 'Interface', 'SATA 6Gb/s' ), array( 'Speed', '7,200 rpm' ), array( 'Workload', '550 TB/year' ), array( 'MTBF', '2.5 million hours' ) ),
			'warranty' => '5 years', 'downloads' => false ),
		array( 'name' => '12TB NAS HDD', 'sku' => 'TN-HDD-12T', 'cat' => 'HDD', 'brand' => 'Western Digital', 'img' => 'hdd-nas', 'price' => '259', 'sale' => '239', 'stock' => 50, 'featured' => false,
			'short' => 'NAS-optimised hard drive for 24/7 file servers and backup appliances.',
			'attrs' => array( 'Capacity' => '12TB', 'Interface' => 'SATA', 'Form Factor' => '3.5 inch', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Capacity', '12TB' ), array( 'Interface', 'SATA 6Gb/s' ), array( 'Speed', '7,200 rpm' ), array( 'Rated for', 'Up to 24 bays' ) ),
			'warranty' => '5 years', 'downloads' => false ),
		array( 'name' => 'Backup Storage Appliance (8-Bay NAS)', 'sku' => 'TN-NAS-8BAY', 'cat' => 'Storage', 'brand' => 'Synology', 'img' => 'nas', 'price' => '1890', 'sale' => '', 'stock' => 6, 'featured' => true,
			'short' => '8-bay rackmount storage appliance for immutable backups, snapshots and replication.',
			'attrs' => array( 'Capacity' => 'Diskless', 'Interface' => 'SATA', 'Form Factor' => '2U Rack', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Drive bays', '8 × 3.5"/2.5" SATA' ), array( 'Network', '4 × 1GbE + 2 × 10GbE SFP+' ), array( 'Memory', '16GB ECC' ), array( 'Features', 'Immutable snapshots, replication, encryption' ), array( 'Form factor', '2U rack' ) ),
			'warranty' => '5 years', 'downloads' => true, 'cross' => array( 'TN-HDD-18T', 'TN-HDD-12T', 'TN-UPS-3K' ) ),

		// ---------------------------------------------------- Components.
		array( 'name' => 'Enterprise DDR5 ECC RAM (RDIMM)', 'sku' => 'TN-RAM-DDR5', 'cat' => 'RAM', 'brand' => 'Kingston', 'img' => 'ram', 'price' => '', 'sale' => '', 'stock' => -1, 'featured' => true,
			'variable' => array( 'RAM' => array( '32GB' => array( '189', 50 ), '64GB' => array( '349', 30 ), '128GB' => array( '729', 0 ) ) ),
			'short' => 'Registered ECC DDR5-4800 memory validated for current Xeon and EPYC platforms.',
			'attrs' => array( 'Form Factor' => 'RDIMM', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Type', 'DDR5 RDIMM ECC' ), array( 'Speed', '4800 MT/s' ), array( 'Voltage', '1.1V' ), array( 'Rank', '2Rx8 / 2Rx4' ) ),
			'warranty' => 'Lifetime', 'downloads' => false ),
		array( 'name' => 'DDR4 ECC RDIMM 32GB', 'sku' => 'TN-RAM-DDR4-32', 'cat' => 'RAM', 'brand' => 'Kingston', 'img' => 'ram-ddr4', 'price' => '119', 'sale' => '', 'stock' => 80, 'featured' => false,
			'short' => '32GB DDR4-3200 registered ECC module for previous-generation servers.',
			'attrs' => array( 'RAM' => '32GB', 'Form Factor' => 'RDIMM', 'Warranty' => 'Lifetime' ),
			'specs' => array( array( 'Capacity', '32GB' ), array( 'Speed', '3200 MT/s' ), array( 'Type', 'DDR4 RDIMM ECC' ) ),
			'warranty' => 'Lifetime', 'downloads' => false ),
		array( 'name' => 'Intel Xeon Gold 6430 Processor', 'sku' => 'TN-CPU-6430', 'cat' => 'CPUs', 'brand' => 'Intel', 'img' => 'cpu-intel', 'price' => '2120', 'sale' => '', 'stock' => 10, 'featured' => false,
			'short' => '32-core server processor for dual-socket platforms.',
			'attrs' => array( 'Processor' => 'Intel Xeon Gold', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Cores / threads', '32 / 64' ), array( 'Base / turbo', '2.1 / 3.4 GHz' ), array( 'Cache', '60 MB' ), array( 'TDP', '270W' ), array( 'Memory', 'DDR5-4400, 8 channels' ) ),
			'warranty' => '3 years', 'downloads' => false ),
		array( 'name' => 'AMD EPYC 9354 Processor', 'sku' => 'TN-CPU-9354', 'cat' => 'CPUs', 'brand' => 'AMD', 'img' => 'cpu-amd', 'price' => '3420', 'sale' => '3290', 'stock' => 6, 'featured' => false,
			'short' => '32-core server processor with 12 DDR5 memory channels.',
			'attrs' => array( 'Processor' => 'AMD EPYC', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Cores / threads', '32 / 64' ), array( 'Base / boost', '3.25 / 3.8 GHz' ), array( 'Cache', '256 MB L3' ), array( 'TDP', '280W' ), array( 'Memory', 'DDR5-4800, 12 channels' ) ),
			'warranty' => '3 years', 'downloads' => false ),
		array( 'name' => 'Data Center GPU 48GB (NVIDIA L40S)', 'sku' => 'TN-GPU-L40S', 'cat' => 'GPUs', 'brand' => 'NVIDIA', 'img' => 'gpu', 'price' => '9890', 'sale' => '', 'stock' => 2, 'featured' => true,
			'short' => 'Passively cooled data center GPU for AI inference, rendering and virtual workstations.',
			'attrs' => array( 'RAM' => '48GB', 'Interface' => 'PCIe', 'Form Factor' => 'PCIe', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Memory', '48GB GDDR6 with ECC' ), array( 'Interface', 'PCIe 4.0 x16' ), array( 'Cooling', 'Passive (server airflow required)' ), array( 'Max power', '350W' ) ),
			'warranty' => '3 years', 'downloads' => false, 'cross' => array( 'TN-SRV-R760' ) ),

		// -------------------------------------------------- Racks, UPS, power.
		array( 'name' => '42U Server Rack Cabinet', 'sku' => 'TN-RACK-42U', 'cat' => 'Racks', 'brand' => 'TechNova Labs', 'img' => 'rack', 'price' => '1150', 'sale' => '', 'stock' => 5, 'featured' => false,
			'short' => '600 × 1000 mm cabinet with perforated doors, cable management and casters.',
			'attrs' => array( 'Form Factor' => '42U', 'Warranty' => '5 Years' ),
			'specs' => array( array( 'Height', '42U' ), array( 'Dimensions', '600 × 1000 × 2000 mm' ), array( 'Load rating', '1,300 kg static' ), array( 'Doors', 'Perforated, lockable' ) ),
			'warranty' => '5 years', 'downloads' => false, 'cross' => array( 'TN-PDU-16A', 'TN-UPS-3K' ) ),
		array( 'name' => 'Online UPS 3kVA Rack/Tower', 'sku' => 'TN-UPS-3K', 'cat' => 'UPS', 'brand' => 'APC', 'img' => 'ups', 'price' => '1290', 'sale' => '', 'stock' => 9, 'featured' => true,
			'short' => 'Double-conversion online UPS with network management slot and hot-swap batteries.',
			'attrs' => array( 'Capacity' => '3kVA', 'Form Factor' => '2U Rack', 'Warranty' => '2 Years' ),
			'specs' => array( array( 'Capacity', '3000VA / 2700W' ), array( 'Topology', 'Online double-conversion' ), array( 'Runtime', 'About 8 minutes at full load' ), array( 'Outlets', '8 × C13, 1 × C19' ) ),
			'warranty' => '2 years (batteries 1 year)', 'downloads' => true ),
		array( 'name' => 'Metered Rack PDU 16A', 'sku' => 'TN-PDU-16A', 'cat' => 'Accessories', 'brand' => 'APC', 'img' => 'pdu', 'price' => '349', 'sale' => '', 'stock' => 25, 'featured' => false,
			'short' => 'Zero-U metered power distribution unit with 24 outlets and network monitoring.',
			'attrs' => array( 'Form Factor' => 'Zero-U', 'Warranty' => '2 Years' ),
			'specs' => array( array( 'Input', '16A, IEC 60309' ), array( 'Outlets', '20 × C13, 4 × C19' ), array( 'Metering', 'Per-unit, network-enabled' ) ),
			'warranty' => '2 years', 'downloads' => false ),

		// -------------------------------------------------- Networking misc.
		array( 'name' => 'Network Management Appliance (NMS-100)', 'sku' => 'TN-NMS-100', 'cat' => 'Networking', 'brand' => 'TechNova Labs', 'img' => 'nms', 'price' => '2490', 'sale' => '', 'stock' => 4, 'featured' => false,
			'short' => 'Pre-configured 1U monitoring appliance with network discovery, alerting and configuration backup.',
			'attrs' => array( 'Form Factor' => '1U Rack', 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Monitoring', 'SNMP, NetFlow/sFlow, syslog' ), array( 'Capacity', 'Up to 1,000 devices' ), array( 'Storage', '2 × 960GB SSD, RAID 1' ), array( 'Network', '4 × 1GbE' ), array( 'Includes', 'Dashboards, alerting, config backup' ) ),
			'warranty' => '3 years', 'downloads' => true ),
		array( 'name' => 'Wi-Fi 6E Enterprise Access Point', 'sku' => 'TN-AP-WIFI6E', 'cat' => 'Networking', 'brand' => 'Ubiquiti', 'img' => 'ap', 'price' => '329', 'sale' => '299', 'stock' => 40, 'featured' => false,
			'short' => 'Tri-band ceiling access point for high-density offices, campuses and retail.',
			'attrs' => array( 'Port Speed' => '2.5GbE', 'Interface' => 'RJ45', 'Form Factor' => 'Ceiling', 'Warranty' => '1 Year' ),
			'specs' => array( array( 'Standard', 'Wi-Fi 6E (802.11ax)' ), array( 'Bands', '2.4 / 5 / 6 GHz' ), array( 'Uplink', '2.5GbE PoE+' ), array( 'Clients', '300+ concurrent' ) ),
			'warranty' => '1 year', 'downloads' => false, 'cross' => array( 'TN-SW-POE24' ) ),

		// ------------------------------------------------ Software & licenses.
		array( 'name' => 'Server OS Datacenter License (16-Core)', 'sku' => 'TN-LIC-DC16', 'cat' => 'Licenses', 'brand' => 'Microsoft', 'img' => 'license', 'price' => '6155', 'sale' => '', 'stock' => -1, 'featured' => false, 'virtual' => true,
			'short' => 'Perpetual 16-core datacenter licence with unlimited virtualization rights. Delivered electronically.',
			'attrs' => array( 'Warranty' => 'N/A' ),
			'specs' => array( array( 'Licensing', 'Per core (16-core pack)' ), array( 'Virtualization', 'Unlimited virtual machines' ), array( 'Delivery', 'Electronic, by email' ) ),
			'warranty' => 'Not applicable (software licence)', 'downloads' => false ),
		array( 'name' => 'Endpoint Protection Suite — 50 Devices / 1 Year', 'sku' => 'TN-LIC-EPP50', 'cat' => 'Licenses', 'brand' => 'TechNova Labs', 'img' => 'license-epp', 'price' => '1450', 'sale' => '1290', 'stock' => -1, 'featured' => false, 'virtual' => true,
			'short' => 'Centrally managed anti-malware, device control and vulnerability reporting for 50 devices.',
			'attrs' => array( 'Warranty' => 'N/A' ),
			'specs' => array( array( 'Devices', '50 (Windows, macOS, Linux)' ), array( 'Term', '12 months' ), array( 'Management', 'Cloud console' ), array( 'Delivery', 'Electronic' ) ),
			'warranty' => 'Subscription — support included for the term', 'downloads' => false ),

		// ------------------------------------------------- Support & services.
		array( 'name' => 'Linux Server Support Package (Monthly)', 'sku' => 'TN-SVC-LINUX-SUP', 'cat' => 'Support', 'brand' => 'TechNova Labs', 'img' => 'service-support', 'price' => '149', 'sale' => '', 'stock' => -1, 'featured' => false, 'virtual' => true,
			'short' => 'Monitoring, patching, backups verification and 8×5 engineer support for one Linux server.',
			'attrs' => array( 'Warranty' => 'N/A' ),
			'specs' => array( array( 'Coverage', '1 Linux server (physical or virtual)' ), array( 'Includes', 'Monitoring, monthly patching, backup checks' ), array( 'Support hours', 'Business hours, 8×5' ), array( 'Response target', '4 business hours' ) ),
			'warranty' => 'Service term: monthly, cancel anytime', 'downloads' => false ),
		array( 'name' => 'Managed Network Support (Monthly, per site)', 'sku' => 'TN-SVC-MANAGED-NET', 'cat' => 'Support', 'brand' => 'TechNova Labs', 'img' => 'service-managed', 'price' => '390', 'sale' => '', 'stock' => -1, 'featured' => true, 'virtual' => true,
			'short' => '24/7 monitoring, configuration backup and change management for one site’s network.',
			'attrs' => array( 'Warranty' => 'N/A' ),
			'specs' => array( array( 'Coverage', 'Up to 10 network devices at one site' ), array( 'Monitoring', '24/7 with alerting' ), array( 'Includes', 'Config backup, firmware updates, quarterly report' ), array( 'Response target', '1 hour for critical incidents' ) ),
			'warranty' => 'Service term: 12 months', 'downloads' => false ),
		array( 'name' => 'Cybersecurity Assessment', 'sku' => 'TN-SVC-SEC-ASSESS', 'cat' => 'Support', 'brand' => 'TechNova Labs', 'img' => 'service-security', 'price' => '2900', 'sale' => '', 'stock' => -1, 'featured' => false, 'virtual' => true,
			'short' => 'Two-week assessment of your network, identity and endpoint security with a prioritised action plan.',
			'attrs' => array( 'Warranty' => 'N/A' ),
			'specs' => array( array( 'Duration', 'About 2 weeks' ), array( 'Scope', 'Network, identity, endpoints, backups' ), array( 'Deliverables', 'Findings report and prioritised roadmap' ), array( 'Format', 'Remote with optional on-site day' ) ),
			'warranty' => 'Fixed-scope professional service', 'downloads' => false ),
		array( 'name' => 'Cloud Migration Service (Starter)', 'sku' => 'TN-SVC-CLOUD-MIG', 'cat' => 'Support', 'brand' => 'TechNova Labs', 'img' => 'service-cloud', 'price' => '4900', 'sale' => '', 'stock' => -1, 'featured' => false, 'virtual' => true,
			'short' => 'Readiness assessment, landing zone and migration of up to 10 workloads to your chosen cloud.',
			'attrs' => array( 'Warranty' => 'N/A' ),
			'specs' => array( array( 'Workloads', 'Up to 10 virtual machines or apps' ), array( 'Includes', 'Assessment, landing zone, migration, handover' ), array( 'Clouds', 'AWS, Azure or Google Cloud' ), array( 'Hypercare', '30 days after migration' ) ),
			'warranty' => 'Fixed-scope professional service', 'downloads' => false ),
		array( 'name' => 'Extended Warranty — 3 Years Next Business Day', 'sku' => 'TN-SVC-WARRANTY3', 'cat' => 'Support', 'brand' => 'TechNova Labs', 'img' => 'service-warranty', 'price' => '390', 'sale' => '', 'stock' => -1, 'featured' => false, 'virtual' => true,
			'short' => 'Extend hardware cover to three years with next-business-day parts replacement.',
			'attrs' => array( 'Warranty' => '3 Years' ),
			'specs' => array( array( 'Term', '3 years from delivery' ), array( 'Response', 'Next business day parts' ), array( 'Applies to', 'Servers, switches and storage bought from us' ) ),
			'warranty' => '3 years', 'downloads' => false ),
	);
}
