<?php
/**
 * Cut-out manifest — generated by tools/make-cutouts.py, do not hand-edit.
 *
 * Each entry maps a product slug to its transparent photograph and to the
 * BODY BOX inside that photograph, as fractions of the image: [x, y, w, h].
 *
 * The body box is what makes the photograph usable. The measurements on the
 * page describe the bag body, not the strap, so the plugin scales the image
 * until the body box matches the real centimetres and lets the strap fall
 * where it may. Each box was found by searching the silhouette for the
 * rectangle whose aspect equals the product's own measured aspect, so the
 * photograph is placed at true size with no distortion at all.
 */

defined( 'ABSPATH' ) || exit;

return array(
	'chic-metal-lock-pu-leather-pillow-handbag-for-women' => array( 'file' => 'chic-metal-lock-pu-leather-pillow-handbag-for-women.webp', 'body' => array( 0.0321, 0.3603, 0.9571, 0.6358 ) ),
	'elegant-evening-clutch-bag-for-women' => array( 'file' => 'elegant-evening-clutch-bag-for-women.webp', 'body' => array( 0.006, 0.1253, 0.9879, 0.8699 ) ),
	'elegant-flap-pu-leather-crossbody-bag-for-women' => array( 'file' => 'elegant-flap-pu-leather-crossbody-bag-for-women.webp', 'body' => array( 0.0857, 0.0, 0.7821, 1.0 ) ),
	'elegant-pu-leather-handbag-for-women' => array( 'file' => 'elegant-pu-leather-handbag-for-women.webp', 'body' => array( 0.0043, 0.4107, 0.9957, 0.5839 ) ),
	'elegant-round-pleated-dinner-clutch-bag-for-women' => array( 'file' => 'elegant-round-pleated-dinner-clutch-bag-for-women.webp', 'body' => array( 0.0319, 0.0973, 0.9361, 0.8429 ) ),
	'fashion-vegetable-tanned-leather-rodeo-crossbody-bag-for-women' => array( 'file' => 'fashion-vegetable-tanned-leather-rodeo-crossbody-bag-for-women.webp', 'body' => array( 0.0372, 0.5732, 0.9599, 0.35 ) ),
	'fashionable-high-end-chain-small-square-shoulder-bag-for-women' => array( 'file' => 'fashionable-high-end-chain-small-square-shoulder-bag-for-women.webp', 'body' => array( 0.0036, 0.042, 0.9875, 0.9475 ) ),
	'fashionable-pu-leather-shoulder-bag-for-women' => array( 'file' => 'fashionable-pu-leather-shoulder-bag-for-women.webp', 'body' => array( 0.0159, 0.5857, 0.9683, 0.4018 ) ),
	'large-capacity-monogram-pattern-commuter-tote-bag' => array( 'file' => 'large-capacity-monogram-pattern-commuter-tote-bag.webp', 'body' => array( 0.0023, 0.4339, 0.993, 0.5321 ) ),
	'luxurious-large-capacity-pu-leather-commuter-tote-bag-for-women' => array( 'file' => 'luxurious-large-capacity-pu-leather-commuter-tote-bag-for-women.webp', 'body' => array( 0.0505, 0.3964, 0.9472, 0.5054 ) ),
	'magnetic-flap-pu-leather-shoulder-bag-for-women' => array( 'file' => 'magnetic-flap-pu-leather-shoulder-bag-for-women.webp', 'body' => array( 0.0299, 0.4857, 0.9502, 0.4536 ) ),
	'retro-artistic-style-embroidered-crossbody-bag-for-women' => array( 'file' => 'retro-artistic-style-embroidered-crossbody-bag-for-women.webp', 'body' => array( 0.1786, 0.2599, 0.7589, 0.7137 ) ),
	'soft-pu-leather-shoulder-bag-for-women' => array( 'file' => 'soft-pu-leather-shoulder-bag-for-women.webp', 'body' => array( 0.0589, 0.0157, 0.8625, 0.9748 ) ),
	'stylish-pu-leather-crossbody-bag-for-women' => array( 'file' => 'stylish-pu-leather-crossbody-bag-for-women.webp', 'body' => array( 0.0536, 0.1218, 0.8018, 0.8706 ) ),
	'trendy-pu-leather-tote-bag-for-women' => array( 'file' => 'trendy-pu-leather-tote-bag-for-women.webp', 'body' => array( 0.0302, 0.5393, 0.9488, 0.4536 ) ),
	'velvet-rhinestone-evening-clutch-bag-for-women' => array( 'file' => 'velvet-rhinestone-evening-clutch-bag-for-women.webp', 'body' => array( 0.0054, 0.2335, 0.9893, 0.7386 ) ),
	'versatile-soft-pu-leather-shoulder-bag-for-women' => array( 'file' => 'versatile-soft-pu-leather-shoulder-bag-for-women.webp', 'body' => array( 0.1054, 0.0, 0.7964, 1.0 ) ),
	'vintage-tassel-soft-pu-leather-messenger-bag-for-women' => array( 'file' => 'vintage-tassel-soft-pu-leather-messenger-bag-for-women.webp', 'body' => array( 0.1464, 0.0033, 0.7607, 0.9739 ) ),
	'woven-pattern-shoulder-bag-for-women' => array( 'file' => 'woven-pattern-shoulder-bag-for-women.webp', 'body' => array( 0.0714, 0.2755, 0.8786, 0.7122 ) ),
);
