<?php
/**
 * The launch products: content, media map and the full-screen page layout.
 *
 * Specs come from the supplier proforma (the units actually imported) and
 * Breo's own product pages. Media is downloaded into the site's Media Library
 * by the importer (never hot-linked); `crop` = [x, y, w, h] in source pixels,
 * used to cut Breo's baked-in Chinese/English captions off their photos.
 * Order here = order in menus and grids.
 */
defined( 'ABSPATH' ) || exit;

$n6  = 'https://www.breo.com/uploads/20251208/';
$us  = 'https://cdn.shopify.com/s/files/1/0702/5131/5367/files/';
$my  = 'https://cdn.shopify.com/s/files/1/0502/5261/1753/files/';
$lz  = 'https://my-live-01.slatic.net/p/';
$g7  = 'https://cchimg.breo.com/images/jmq7/';

return array(

	/* ================================================================
	 * N6 mini
	 * ============================================================= */
	'N990000631' => array(
		'name'       => 'Breo N6 Mini Neck & Shoulder Massager',
		'short_name' => 'N6 mini',
		'tagline'    => 'Neck & Shoulder Massager',
		'menu_sub'   => 'Heated, hands-free kneading',
		'accent'     => '#e8692c',
		'slug'       => 'breo-n6-mini-neck-shoulder-massager',
		'model'      => 'N6 mini',
		'category'   => 'neck-shoulder-massagers',
		'color'      => 'Orange',
		'weight'     => 1.25,
		'dims'       => array( 28.5, 17, 14 ),
		'short'      => 'Hands-free, heated kneading for the neck and shoulders: plum-blossom rollers, a warm red-light head and a whisper-quiet motor in a 1.25 kg wearable.',
		'badges'     => array( 'Heated 40–45°C head', 'Plum-blossom rollers', 'Cordless & hands-free' ),
		'media'      => array(
			'tile'    => array( 'src' => $us . 'N6_mini_1.png', 'alt' => 'Breo N6 mini neck and shoulder massager' ),
			'desk'    => array( 'src' => $n6 . 'fec1fc31ff2572f22edc688752801c32.jpg', 'alt' => 'Using the Breo N6 mini while working at a laptop', 'focus' => '20% 50%', 'focus_m' => '50% 35%' ),
			'flat'    => array( 'src' => $n6 . '73ba739c117f806f5945266f02ccdbbb.jpg', 'crop' => array( 380, 280, 1180, 300 ), 'alt' => 'Breo N6 mini seen from above' ),
			'roller'  => array( 'src' => $n6 . 'ae84c27c435e0d2eb03bb70a96b0cade.jpg', 'crop' => array( 900, 0, 1020, 850 ), 'alt' => 'Plum-blossom massage roller working on the neck' ),
			'heat'    => array( 'src' => $n6 . 'c3362ba07301bcbe0ec9323a53e89557.jpg', 'crop' => array( 0, 0, 1060, 850 ), 'alt' => 'Far-infrared heat at the base of the neck' ),
			'core'    => array( 'src' => $n6 . '89cd992afbba4552cfd02521d62dcf40.jpg', 'crop' => array( 880, 0, 1040, 853 ), 'alt' => 'The B-tech kneading core inside the N6 mini' ),
			'stretch' => array( 'src' => $n6 . '77273c1bb8af7243db1cf4c03c571699.jpg', 'crop' => array( 900, 0, 1020, 850 ), 'alt' => 'Pulling the straps for a deeper shoulder massage' ),
			'gift'    => array( 'src' => $n6 . 'd191e836475cf7b61b872f6132fe486c.jpg', 'crop' => array( 0, 0, 1080, 850 ), 'alt' => 'Giving the N6 mini as a gift' ),
			'sofa'    => array( 'src' => $n6 . '5bf45e90474303faef38c965568686f6.jpg', 'crop' => array( 600, 0, 1320, 850 ), 'alt' => 'Relaxing on the sofa with the N6 mini' ),
			'ondesk'  => array( 'src' => $n6 . '6f4a63c9816f2f31d265bab1d3dacc35.jpg', 'alt' => 'The N6 mini resting on a desk', 'focus' => '40% 50%' ),
			'dims'    => array( 'src' => $n6 . 'b24b34c3560cc669e18546c6e6522ce0.jpg', 'crop' => array( 0, 250, 750, 514 ), 'alt' => 'N6 mini dimensions: 170 mm wide, 140 mm tall' ),
			'box_unit'  => array( 'src' => $n6 . 'daae529934def87d30b93a7a20736a0e.jpg', 'crop' => array( 500, 270, 400, 340 ), 'alt' => 'N6 mini neck massager' ),
			'box_cable' => array( 'src' => $n6 . 'daae529934def87d30b93a7a20736a0e.jpg', 'crop' => array( 1120, 330, 170, 270 ), 'alt' => 'USB charging cable' ),
		),
		'gallery'    => array( 'desk', 'stretch', 'sofa', 'ondesk', 'gift' ),
		'sections'   => array(
			array( 'type' => 'hero', 'media' => 'desk', 'theme' => 'light', 'align' => 'left',
				'title' => 'Your shoulders, finally off duty',
				'text'  => 'Hands-free heated kneading for the neck and shoulders, made for long days at the desk.' ),
			array( 'type' => 'buy' ),
			array( 'type' => 'center', 'media' => 'flat', 'bg' => 'white', 'id' => 'overview',
				'eyebrow' => 'Breo N6 mini',
				'title'   => 'Push. Roll. Knead.',
				'text'    => 'Three massage motions in one wearable, shaped to sit across your neck and shoulders the way a therapist\'s hands do.' ),
			array( 'type' => 'split', 'media' => 'roller', 'side' => 'right', 'theme' => 'dark',
				'eyebrow' => 'Plum-blossom rollers',
				'title'   => 'From shoulder to back, heat that rolls deep',
				'text'    => 'Clusters of firm nodes press, roll and knead point by point, like the heel of a palm working along the shoulder. The 40–45°C red-light head warms as it massages, so tight muscles let go faster.' ),
			array( 'type' => 'split', 'media' => 'heat', 'side' => 'left', 'theme' => 'dark',
				'eyebrow' => 'Far-infrared warmth',
				'title'   => 'Warmth where the tension starts',
				'text'    => 'Far-infrared heat focuses on the base of the neck, the spot that stiffens first after hours of screen time. Use it with the massage, or switch it off and enjoy the kneading on its own.' ),
			array( 'type' => 'split', 'media' => 'core', 'side' => 'right', 'theme' => 'white',
				'eyebrow' => 'B-tech kneading core',
				'title'   => 'Engineered to feel like hands',
				'text'    => 'A precision gear core reproduces the rhythm of real hand massage and is built to last. A built-in Hall sensor adapts the stroke to the shape of your shoulders for a close, even fit.' ),
			array( 'type' => 'split', 'media' => 'stretch', 'side' => 'right', 'theme' => 'cream',
				'eyebrow' => 'Only 1.25 kg',
				'title'   => 'Wear it. Pull it. Forget it.',
				'text'    => 'Drape it like a scarf and let it work hands-free, or loop your hands through the straps to pull it closer for a deeper massage. It is light enough that it doesn\'t weigh on your neck.' ),
			array( 'type' => 'stats', 'theme' => 'dark', 'items' => array(
				array( '40–45', '°C', 'Heated massage head' ),
				array( '<55', 'dB', 'Whisper-quiet motor' ),
				array( '2500', 'mAh', 'Cordless battery' ),
				array( '1.25', 'kg', 'Light on the shoulders' ),
			) ),
			array( 'type' => 'split', 'media' => 'ondesk', 'side' => 'left', 'theme' => 'cream',
				'eyebrow' => 'Home · Office · Travel',
				'title'   => 'Relief between meetings',
				'text'    => 'Cordless and quiet, it goes from the office chair to the sofa to the car without a socket in sight.' ),
			array( 'type' => 'split', 'media' => 'gift', 'side' => 'left', 'theme' => 'warm',
				'eyebrow' => 'The gift of rest',
				'title'   => 'For the people who carry the most',
				'text'    => 'A soft vegan-leather finish and a clean, modern design make it a thoughtful present for parents, partners and anyone who works too hard.' ),
			array( 'type' => 'box' ),
			array( 'type' => 'specs', 'media' => 'dims' ),
			array( 'type' => 'usage_faq' ),
			array( 'type' => 'related' ),
		),
		'specs'      => array(
			'Product Name'     => 'Breo Neck Massager',
			'Model'            => 'N6 mini',
			'Rated Voltage'    => '5V ⎓',
			'Rated Power'      => '10W',
			'Battery Capacity' => '2500mAh',
			'Heated Head'      => '40–45°C',
			'Noise Level'      => '<55dB',
			'Product Weight'   => '1250g',
			'Dimensions'       => 'L285 × W170 × H140 mm',
			'Color'            => 'Orange',
		),
		'box'        => array(
			array( 'N6 mini neck massager', 'box_unit' ),
			array( 'Charging cable', 'box_cable' ),
		),
		'usage'      => array(
			'Rest it over your shoulders with the rollers against the back of your neck.',
			'Start on a gentle setting and adjust to what feels comfortable.',
			'Use it for about 15 minutes per session, up to 2–3 times a day.',
			'Don\'t use it on the front of the neck or while sleeping.',
		),
		'faq'        => array(
			array( 'Can I use it while working at my desk?', 'Yes. It is hands-free and runs under 55dB, so it won\'t disturb anyone.' ),
			array( 'Is it good for older parents?', 'Yes, it is a popular gift. Start gently. Anyone with a medical condition, a pacemaker or a neck injury should ask their doctor first.' ),
			array( 'Can I use it without the heat?', 'Yes. Switch the heat off and use the massage on its own.' ),
		),
	),

	/* ================================================================
	 * See KE
	 * ============================================================= */
	'N910200212' => array(
		'name'       => 'Breo See KE Eye Massager',
		'short_name' => 'See KE',
		'tagline'    => 'Eye Massager',
		'menu_sub'   => 'Warm airbag massage for tired eyes',
		'accent'     => '#e0873a',
		'slug'       => 'breo-see-ke-eye-massager',
		'model'      => 'See KE',
		'category'   => 'eye-massagers',
		'color'      => 'Grey',
		'weight'     => 0.232,
		'dims'       => array( 20.6, 10.9, 7.3 ),
		'short'      => 'Warm compress and 3D airbag massage for tired, screen-strained eyes. Folds flat, weighs 232 g and runs cordless.',
		'badges'     => array( '43°C warm compress', '3D airbag massage', '180° foldable' ),
		'media'      => array(
			'tile'   => array( 'src' => $lz . '156c4ac32394d4ac922c1f1ece502b94.jpg', 'crop' => array( 0, 420, 790, 790 ), 'alt' => 'Breo See KE eye massager in use' ),
			'glow'   => array( 'src' => $lz . '156c4ac32394d4ac922c1f1ece502b94.jpg', 'crop' => array( 0, 380, 790, 860 ), 'alt' => 'The See KE warming the eye area', 'focus' => '50% 40%' ),
			'sofa'   => array( 'src' => $lz . '84a71d0a8b7b91adb506013eeaa31858.jpg', 'crop' => array( 0, 605, 790, 680 ), 'alt' => 'Relaxing on the sofa with the See KE' ),
			'night'  => array( 'src' => $lz . '92c4850eb4231089c5b3663d954fe45e.jpg', 'crop' => array( 0, 330, 790, 970 ), 'alt' => 'Winding down at night with the See KE' ),
			'airbag' => array( 'src' => $lz . 'c6a8dc8589923c705b5ac36f7af620ba.jpg', 'crop' => array( 0, 450, 790, 850 ), 'alt' => 'The See KE covering the whole eye area' ),
			'fold'   => array( 'src' => $lz . '2b4f91c80ec225d8389d122cad9f350c.jpg', 'crop' => array( 0, 420, 790, 877 ), 'alt' => 'Folding the See KE into a handbag' ),
			'boxed'  => array( 'src' => $lz . '66bfff3a2a989554e362928cca399763.jpg', 'crop' => array( 0, 0, 790, 600 ), 'alt' => 'See KE gift box, manual, cable and massager' ),
			'box_mask'   => array( 'src' => $lz . '66bfff3a2a989554e362928cca399763.jpg', 'crop' => array( 440, 290, 280, 230 ), 'alt' => 'See KE eye massager' ),
			'box_manual' => array( 'src' => $lz . '66bfff3a2a989554e362928cca399763.jpg', 'crop' => array( 140, 400, 150, 150 ), 'alt' => 'See KE user manual' ),
			'box_gift'   => array( 'src' => $lz . '66bfff3a2a989554e362928cca399763.jpg', 'crop' => array( 70, 15, 300, 270 ), 'alt' => 'See KE gift box' ),
			'cable'      => array( 'src' => $g7 . '12_5.png', 'alt' => 'USB Type-C charging cable' ),
		),
		'gallery'    => array( 'glow', 'sofa', 'fold', 'night', 'boxed' ),
		'sections'   => array(
			array( 'type' => 'hero_split', 'media' => 'glow', 'theme' => 'warm',
				'title' => 'Ten minutes. Eyes closed. Reset.',
				'text'  => 'Gentle warmth and rhythmic airbag massage for eyes that stare at screens all day.' ),
			array( 'type' => 'buy' ),
			array( 'type' => 'stats', 'theme' => 'cream', 'id' => 'overview', 'items' => array(
				array( '43', '°C', 'Constant warm compress' ),
				array( '8', '', 'Key points around the eyes' ),
				array( '232', 'g', 'About a smartphone' ),
				array( '180', '°', 'Folds flat to pack' ),
			) ),
			array( 'type' => 'split', 'media' => 'airbag', 'side' => 'left', 'theme' => 'white',
				'eyebrow' => 'Zoned 3D airbag massage',
				'title'   => 'A slow, careful eye massage',
				'text'    => 'Air chambers inflate and release in a rhythm around the eyes, working the 8 key pressure points of the eye area without pressing on the eyeball.' ),
			array( 'type' => 'split', 'media' => 'glow', 'side' => 'right', 'theme' => 'warm',
				'eyebrow' => 'Warm compress',
				'title'   => 'A steady 43°C, like a warm towel that never cools',
				'text'    => 'A temperature sensor keeps the warmth even for the whole session, helping tense eye muscles relax after long hours on screens.' ),
			array( 'type' => 'split', 'media' => 'night', 'side' => 'left', 'theme' => 'dark',
				'eyebrow' => 'Temples too',
				'title'   => 'For late nights and long screens',
				'text'    => 'Separate temple massage points ease the tightness that builds at the sides of the head, and built-in calming music helps you switch off before bed. Double-tap to mute it.' ),
			array( 'type' => 'split', 'media' => 'fold', 'side' => 'right', 'theme' => 'cream',
				'eyebrow' => '180° foldable · 232 g',
				'title'   => 'Folds in half. Goes everywhere.',
				'text'    => 'Soft, flexible materials fold without creasing, so it slips into a handbag, desk drawer or carry-on. One charge covers about a week of daily sessions.' ),
			array( 'type' => 'box' ),
			array( 'type' => 'specs' ),
			array( 'type' => 'usage_faq' ),
			array( 'type' => 'related' ),
		),
		'specs'      => array(
			'Product Name'     => 'Breo Eye Massager',
			'Model'            => 'See KE',
			'Rated Voltage'    => '5V DC',
			'Rated Power'      => '5W',
			'Battery Capacity' => '1050mAh',
			'Warm Compress'    => 'About 43°C, sensor-controlled',
			'Massage'          => '3D airbag + temple massage, 3 modes',
			'Charging'         => 'USB Type-C',
			'Noise Level'      => '≤55dB',
			'Product Weight'   => '232g',
			'Dimensions'       => 'L206 × W109 × H73 mm',
			'Color'            => 'Grey',
		),
		'box'        => array(
			array( 'See KE eye massager', 'box_mask' ),
			array( 'USB Type-C charging cable', 'cable' ),
			array( 'User manual', 'box_manual' ),
			array( 'Gift box', 'box_gift' ),
		),
		'usage'      => array(
			'Take off glasses and contact lenses first.',
			'Use it 1–2 times a day, about 10 minutes per session.',
			'Use the warm compress and the massage together for the best effect.',
			'Rest with your eyes closed for a minute afterwards.',
		),
		'faq'        => array(
			array( 'Is it safe for everyday use?', 'Yes. One or two 10-minute sessions a day is the recommended routine.' ),
			array( 'Who should not use it?', 'Don\'t use it after recent eye surgery, or with eye conditions such as glaucoma, retinal problems or an eye infection, unless your doctor approves.' ),
			array( 'Can I use it with glasses or contact lenses?', 'No. Take both off before use.' ),
		),
	),

	/* ================================================================
	 * P2
	 * ============================================================= */
	'N990000981' => array(
		'name'       => 'Breo P2 Neck & Waist Massager',
		'short_name' => 'P2',
		'tagline'    => 'Neck & Waist Massage Pillow',
		'menu_sub'   => 'Kneading pillow with 5-point heat',
		'accent'     => '#e8903c',
		'slug'       => 'breo-p2-neck-waist-massager',
		'model'      => 'P2',
		'category'   => 'back-waist-massagers',
		'color'      => 'Grey',
		'weight'     => 1.4,
		'dims'       => array( 35, 27, 12 ),
		'short'      => 'A cordless kneading pillow with 5-point infrared heat. Use it behind your neck on the sofa or against your lower back in the office chair.',
		'badges'     => array( '3D kneading heads', 'Heat up to 45°C', 'Cordless, ~100 min' ),
		'media'      => array(
			// Studio shot + text-free crops of Breo's P2 marketing images (as published by
			// Breo's Vietnam reseller o-tech.com.vn; the originals carry Vietnamese captions).
			'tile'   => array( 'src' => 'https://product.hstatic.net/200000849887/product/thumbnail_website_o-tech__6__aaac4ca7957b4616889eb4e8a3b3020e_master.jpg', 'alt' => 'Breo P2 neck and waist massager in grey' ),
			'render' => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-8_b2eef667dacb494fa259cf089d76ae37_master.jpg', 'crop' => array( 150, 640, 700, 693 ), 'alt' => 'Breo P2 massage pillow' ),
			'rug'    => array( 'src' => $my . 'my-11134207-820le-mppzwt12ehvk0c.jpg', 'crop' => array( 0, 400, 1024, 560 ), 'alt' => 'Breo P2 massage pillow' ),
			'heads'  => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-1_d66089b38e2a43d4894c581700b623b9_master.jpg', 'crop' => array( 472, 222, 468, 266 ), 'alt' => 'The four 3D massage heads inside the P2' ),
			'tilt'   => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-3_e2c2b1c400b14a138ca992b1272cda87_master.jpg', 'crop' => array( 68, 872, 868, 395 ), 'alt' => 'The massage core tilts through 15 degrees under the neck' ),
			'hug'    => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-3_e2c2b1c400b14a138ca992b1272cda87_master.jpg', 'crop' => array( 565, 292, 370, 362 ), 'alt' => 'Holding the warm P2 like a cushion' ),
			'neck'   => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-4_d635261e70054e789bdc810789c817f1_master.jpg', 'crop' => array( 72, 772, 408, 398 ), 'alt' => 'Resting the neck on the P2' ),
			'back'   => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-4_d635261e70054e789bdc810789c817f1_master.jpg', 'crop' => array( 514, 772, 416, 398 ), 'alt' => 'The P2 behind the lower back on a sofa' ),
			'belly'  => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-5_b38cb88a0a62482ea74c81c6070688b4_master.jpg', 'crop' => array( 400, 470, 535, 450 ), 'alt' => 'Warming the tummy with the P2' ),
			'button' => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-6_041b1b1da2174f8b8f8d8fff54df22ae_master.jpg', 'crop' => array( 250, 765, 685, 335 ), 'alt' => 'The one-touch button and USB-C port' ),
			'usbc'   => array( 'src' => 'https://product.hstatic.net/200000849887/product/breo-p2-7_539a87991bac46ab87056f4130469f7a_master.jpg', 'crop' => array( 548, 648, 402, 288 ), 'alt' => 'USB-C charging port on the P2' ),
			'cable'  => array( 'src' => $g7 . '12_5.png', 'alt' => 'USB Type-C charging cable' ),
			'manual' => array( 'local' => 'assets/icons/manual.png', 'alt' => 'User manual' ),
		),
		'gallery'    => array( 'render', 'rug', 'neck', 'back', 'belly', 'button', 'hug' ),
		'sections'   => array(
			array( 'type' => 'hero_split', 'media' => 'render', 'theme' => 'dark', 'short' => true,
				'title' => 'Lean back. Let it knead.',
				'text'  => 'One cordless pillow for the places desk work hurts most: your neck, your lower back and your tummy.' ),
			array( 'type' => 'buy' ),
			array( 'type' => 'stats', 'theme' => 'dark', 'id' => 'overview', 'items' => array(
				array( '40–45', '°C', 'Two heat levels' ),
				array( '3,000', 'mm²', 'Warm area' ),
				array( '~100', 'min', 'Per charge' ),
				array( '<50', 'dB', 'Quiet motor' ),
			) ),
			array( 'type' => 'tiles', 'theme' => 'cream',
				'eyebrow' => 'Why it feels different',
				'title'   => 'Firm where it should be, gentle where it matters',
				'items'   => array(
					array( 'tilt', 'Rocks through 15° with you', 'An adaptive seesaw tilts the massage heads through a 15° wave, wrapping the natural curve of your neck, shoulders and back.', 'wide' ),
					array( 'heads', 'Four paw-soft 3D heads', 'They knead and press along each muscle and adapt to your shape, so it feels firm without hurting.' ),
					array( 'belly', 'Warmth over 3,000 mm²', 'Infrared heat at 40°C or 45°C spreads wide instead of one hot spot, and an NTC sensor keeps it steady.' ),
					array( 'button', 'One button, three modes', 'Gentle, strong, or warmth only. One press switches mode, so there are no controls to hunt for.' ),
					array( 'usbc', 'Cordless, charged by USB-C', 'A 2200mAh battery lasts about 100 minutes and charges from the same USB-C charger as your phone.' ),
				) ),
			array( 'type' => 'tiles', 'theme' => 'white',
				'eyebrow' => 'Where to use it',
				'title'   => 'Neck, back or tummy. One pillow.',
				'items'   => array(
					array( 'neck', 'Behind your neck', 'Lie back on the sofa or bed and rest your neck in the curve. The heads knead the base of the skull and the tops of the shoulders.' ),
					array( 'back', 'Against your lower back', 'Tuck it between your back and the sofa, office chair or car seat after long hours of sitting.' ),
					array( 'hug', 'Warm and cosy', 'Choose warmth only and hold it against your tummy for gentle heat on a cold evening.' ),
				) ),
			array( 'type' => 'box' ),
			array( 'type' => 'specs' ),
			array( 'type' => 'usage_faq' ),
			array( 'type' => 'related' ),
		),
		'specs'      => array(
			'Product Name'     => 'Breo Neck and Waist Massager',
			'Model'            => 'P2',
			'Rated Voltage'    => '5V ⎓',
			'Rated Power'      => '10W',
			'Battery Capacity' => '2200mAh (about 100 minutes)',
			'Massage Modes'    => '3 (gentle, strong, heat only)',
			'Heat Levels'      => '40°C, 45°C or off (5 heat points, about 3,000 mm²)',
			'Motor'            => 'Brushless, 2,700 rpm',
			'Noise'            => 'Under 50 dB',
			'Auto Shut-off'    => 'After about 10 minutes',
			'Charging'         => 'USB Type-C',
			'Product Weight'   => '1400g',
			'Dimensions'       => 'L350 × W270 × H120 mm',
			'Color'            => 'Grey',
		),
		'box'        => array(
			array( 'P2 neck & waist massager', 'tile' ),
			array( 'USB Type-C charging cable', 'cable' ),
			array( 'User manual', 'manual' ),
		),
		'usage'      => array(
			'Press and hold the power button for 3 seconds to switch it on or off.',
			'Press once to change mode: gentle massage, strong massage, or heat only.',
			'Double-press to change the heat: high, low or off.',
			'Use it for about 15 minutes per session. Don\'t sleep with it running.',
		),
		'faq'        => array(
			array( 'Can I use it on my back as well as my neck?', 'Yes, it is designed for both. Rest your neck on it when reclining, or place it against your lower back when sitting.' ),
			array( 'Does it need to stay plugged in?', 'No. The built-in 2200mAh battery gives about 100 minutes of cordless use.' ),
			array( 'Who should not use it?', 'Ask a doctor first if you are pregnant, have a pacemaker or a spinal injury, or have reduced sensitivity to heat.' ),
		),
	),

	/* ================================================================
	 * No.7 massage gun
	 * ============================================================= */
	'N990000360' => array(
		'name'       => 'Breo No.7 Massage Gun',
		'short_name' => 'No.7',
		'tagline'    => 'Heated Massage Gun',
		'menu_sub'   => 'Heat + deep percussion, 405 g',
		'accent'     => '#d9707a',
		'slug'       => 'breo-no7-massage-gun',
		'model'      => 'No.7',
		'category'   => 'massage-guns',
		'color'      => 'White / Cream',
		'weight'     => 0.405,
		'dims'       => array( 12, 4.6, 15 ),
		'short'      => 'A 405 g percussion massager with a heated head that warms in seconds, for sore shoulders, tight calves and post-workout knots.',
		'badges'     => array( 'Heats to 45°C in ~5 s', '2,800 strokes/min', 'Only 405 g' ),
		'media'      => array(
			'tile'     => array( 'src' => $us . 'Massager_Gun_10-min.png', 'alt' => 'Breo No.7 massage gun' ),
			'hero'     => array( 'src' => $g7 . '11_1.jpg', 'alt' => 'Using the Breo No.7 on the shoulder', 'focus' => '55% 40%', 'focus_m' => '63% 30%' ),
			'arm'      => array( 'src' => $g7 . '11_2.jpg', 'alt' => 'Massaging the arm with the No.7', 'focus' => '35% 50%', 'focus_m' => '52% 40%' ),
			'calf'     => array( 'src' => $g7 . '8_1.jpg', 'alt' => 'Massaging the calf with the No.7', 'focus' => '30% 50%', 'focus_m' => '42% 50%' ),
			'float'    => array( 'src' => $g7 . '11_3.jpg', 'alt' => 'The Breo No.7 massage gun' ),
			'gym'      => array( 'src' => $us . 'Frame_2224.jpg', 'alt' => 'Post-workout recovery with the No.7' ),
			'gym2'     => array( 'src' => $us . 'Frame_2225.jpg', 'alt' => 'Shoulder massage after training' ),
			'product'  => array( 'src' => $g7 . '2_1.jpg', 'alt' => 'No.7 massage gun' ),
			'h_cone'   => array( 'src' => $g7 . '12_2.png', 'alt' => 'Black magnetic cone head' ),
			'h_multi'  => array( 'src' => $g7 . '12_3.png', 'alt' => 'Multi-point massage head' ),
			'h_ball'   => array( 'src' => $g7 . '12_4.png', 'alt' => 'Spherical massage head' ),
			'cable'    => array( 'src' => $g7 . '12_5.png', 'alt' => 'Type-C charging cable' ),
			'bag'      => array( 'src' => $g7 . '12_6.png', 'alt' => 'Carry bag' ),
			'dims'     => array( 'src' => $g7 . '13_1.png', 'alt' => 'No.7 dimensions: 120 mm by 150 mm' ),
			'v_heads'  => array( 'src' => $g7 . '01_%E9%BB%91%E7%A3%81%E9%94%A5%E5%A4%B4.mp4', 'type' => 'video' ),
			'v_heat'   => array( 'src' => $g7 . '02_%E7%83%AD%E9%9C%87%E6%8F%89%E5%8E%8B.mp4', 'type' => 'video' ),
			'v_heat2'  => array( 'src' => $g7 . '03_%E9%BB%91%E5%BA%95%E7%83%AD%E9%9C%87.mp4', 'type' => 'video' ),
			'v_power'  => array( 'src' => $g7 . '04_%E9%AB%98%E6%95%880004.mp4', 'type' => 'video' ),
			'v_metal'  => array( 'src' => $g7 . '05_%E5%85%A8%E9%87%91%E5%B1%9E%E4%BC%A0%E5%8A%A8%E7%B3%BB%E7%BB%9F.mp4', 'type' => 'video' ),
			'v_quiet'  => array( 'src' => $g7 . '06_%E4%BD%8E%E5%99%AA%E9%AB%98%E6%95%88.mp4', 'type' => 'video' ),
		),
		'gallery'    => array( 'hero', 'float', 'arm', 'calf', 'gym' ),
		'sections'   => array(
			array( 'type' => 'hero', 'media' => 'hero', 'theme' => 'light', 'align' => 'left',
				'title' => 'Heat and deep percussion, in the palm of your hand',
				'text'  => 'A 405 g massage gun with a heated head that warms in seconds, for sore shoulders, tight calves and post-workout knots.' ),
			array( 'type' => 'buy' ),
			array( 'type' => 'center', 'media' => 'float', 'bg' => 'cream', 'id' => 'overview', 'full' => true,
				'eyebrow' => 'Breo No.7',
				'title'   => 'Small enough for any bag. Strong enough for any knot.' ),
			array( 'type' => 'split', 'media' => 'v_heads', 'side' => 'right', 'theme' => 'white',
				'eyebrow' => 'Three massage heads',
				'title'   => 'The right head for every muscle',
				'text'    => 'The black magnetic cone head pinpoints knots and pressure points. The soft multi-point head spreads the impact for a gentler tap. The spherical head covers big areas like thighs and back, like the pressure of a palm.' ),
			array( 'type' => 'split', 'media' => 'v_heat', 'side' => 'left', 'theme' => 'white',
				'eyebrow' => 'Hot-VIB Sync',
				'title'   => 'Warms up in about five seconds',
				'text'    => 'The heated ball head reaches a steady 45°C in around five seconds, then pairs that warmth with vibration, like being kneaded by a warm palm.',
				'note'    => '45°C is the head temperature at steady state. Keep it moving and don\'t hold it on one spot.' ),
			array( 'type' => 'film', 'media' => 'v_heat2', 'align' => 'right', 'theme' => 'dark', 'ratio' => '1920 / 850',
				'eyebrow' => 'Even, controlled heat',
				'title'   => 'Constant warmth, monitored in real time',
				'text'    => 'A PI heating film inside the head is watched by an NTC sensor, keeping the temperature even and comfortable while the motor drives heat and vibration together.' ),
			array( 'type' => 'film', 'media' => 'v_metal', 'align' => 'right', 'theme' => 'dark', 'ratio' => '1908 / 850',
				'eyebrow' => 'All-metal drivetrain',
				'title'   => '2,800 strokes a minute, straight to the knot',
				'text'    => 'An all-metal transmission holds a steady 2,800 strokes per minute, with a 10 mm stroke and 8–10 kg of push force that reaches deep into the muscle.' ),
			array( 'type' => 'split', 'media' => 'v_power', 'side' => 'right', 'theme' => 'white',
				'eyebrow' => 'Three intensity levels',
				'title'   => 'Gentle on the neck, serious on the legs',
				'text'    => 'Choose the level for each area: light on sensitive spots, deeper on big muscles. Precise strokes do the work, so you never need to press hard.' ),
			array( 'type' => 'split', 'media' => 'v_quiet', 'side' => 'left', 'theme' => 'white',
				'eyebrow' => 'Low noise',
				'title'   => 'Quiet enough for anywhere',
				'text'    => 'A custom brushless motor runs at around 50 dB, so you can use it at your desk or while the family watches TV.',
				'note'    => 'Breo lab test: level 1, no head attached, measured at 30 cm.' ),
			array( 'type' => 'banner', 'media' => 'arm', 'align' => 'right', 'theme' => 'light',
				'eyebrow' => 'The 7-shaped grip',
				'title'   => 'Shaped for your own hand',
				'text'    => 'The flowing 7-shaped body sits naturally in the palm whichever way you hold it, so you can reach your shoulders, arms and back on your own.' ),
			array( 'type' => 'stats', 'theme' => 'dark', 'items' => array(
				array( '45', '°C', 'Heated head' ),
				array( '2,800', '/min', 'Percussion strokes' ),
				array( '8–10', 'kg', 'Push force' ),
				array( '405', 'g', 'Total weight' ),
			) ),
			array( 'type' => 'banner', 'media' => 'calf', 'align' => 'right', 'theme' => 'light',
				'eyebrow' => 'Recovery, anywhere',
				'title'   => 'After football. After the gym. After the commute.',
				'text'    => 'Light enough for a gym bag, a desk drawer or a suitcase. The carry bag is in the box.' ),
			array( 'type' => 'box' ),
			array( 'type' => 'specs', 'media' => 'dims' ),
			array( 'type' => 'usage_faq' ),
			array( 'type' => 'related' ),
		),
		'specs'      => array(
			'Product Name'     => 'Breo Massage Gun',
			'Model'            => 'No.7 (Sport-M0220)',
			'Rated Voltage'    => '5V ⎓',
			'Rated Power'      => '10W',
			'Battery Capacity' => '2500mAh',
			'Heated Head'      => 'About 45°C, warms in ~5 seconds',
			'Speed'            => 'Up to 2,800 strokes/min',
			'Stroke / Force'   => '10 mm / 8–10 kg',
			'Intensity Levels' => '3',
			'Noise Level'      => 'About 50dB',
			'Charging'         => 'USB Type-C',
			'Product Weight'   => '405g',
			'Dimensions'       => 'L120 × W46 × H150 mm',
			'Color'            => 'White / Cream',
		),
		'box'        => array(
			array( 'No.7 massage gun', 'product' ),
			array( 'Black magnetic cone head', 'h_cone' ),
			array( 'Multi-point massage head', 'h_multi' ),
			array( 'Spherical massage head', 'h_ball' ),
			array( 'Type-C charging cable', 'cable' ),
			array( 'Carry bag', 'bag' ),
		),
		'usage'      => array(
			'Start on the lowest level and move the head slowly along the muscle.',
			'Spend 1–2 minutes per muscle group. A full session needs no more than 10–15 minutes.',
			'Stay on soft muscle. Avoid bones, joints, the spine, the front of the neck and the head.',
			'Don\'t use it on injuries, bruises, swelling or broken skin.',
		),
		'faq'        => array(
			array( 'Is it strong enough for athletes?', 'Yes. 2,800 strokes a minute with 8–10 kg of push force gives real deep-tissue relief, and the heat helps tight muscles release faster.' ),
			array( 'Is it suitable for older people?', 'Yes, on the lowest level. Anyone with a medical condition, a pacemaker or recent surgery should ask their doctor first.' ),
			array( 'Can I take it when travelling?', 'Yes. It weighs only 405 g and comes with a carry bag.' ),
		),
	),
);
